name: Python tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black==22.3.0
          pip install mypy==0.910
          pip install pytest==6.2.4
      - name: Check PEP8 compliance
        run: |
          black --check --verbose src
      - name: Lint with mypy
        run: |
          mypy src
      - name: Unit Integration tests with pytest
        run: |
          pytest --cov=src